apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  selector:
    name: webapp
    version: "1.10" 
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  
